import { TranslationKeysAll, useTranslate } from "hooks";
import Head from "next/head";
import { useRouter } from "next/router";

const Helmet: React.FC<{ title?: string }> = ({
  title,
  children,
}): React.ReactElement => {
  const { pathname } = useRouter();
  const { t } = useTranslate();

  function capitalizeFirstLetter(string: string) {
    const words = string.split(" ");
    return words
      .map((word) => {
        return word[0].toUpperCase() + word.substring(1);
      })
      .join("");
  }

  // const tit =
  //   pathname === "/"
  //     ? t(Dic.dashboard)
  //     : (menuUs as any)[
  //         capitalizeFirstLetter(pathname?.split("/")[1].split("-").join(" "))
  //       ];
  const tit =
    pathname === "/"
      ? t("dashboard")
      : t(
          capitalizeFirstLetter(
            pathname?.split("/")[1].split("-").join(" ")
          ) as TranslationKeysAll
        );

  const res = tit ? "panel" + " | " + tit : "panel";
  return (
    <>
      <Head>
        <title>{res || title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
    </>
  );
};

export default Helmet;
